- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/core/services/connection-status-observer.service.ts
- src/app/core/services/rundown-event-observer.service.ts
- src/app/shared/services/connection-error.service.spec.ts
- src/app/shared/services/connection-error.service.ts
- src/app/shared/shared.module.ts
- src/styles.scss
Displays a snackbar on connection loss and on re-established connection.
> Sof 1593/show notification on connection lost

- src/app/rundown/components/rundown/rundown.component.scss
Disables text selection in RundownView.
> style: Text can't be selected in RundownComponent.

- src/app/core/models/auto-next.ts
- src/app/core/models/part.spec.ts
- src/app/core/models/part.ts
- src/app/core/parsers/zod-entity-parser.service.ts
- src/app/rundown/components/piece/piece.component.scss
_**Note:** Depends on https://github.com/tv2/sofie-server/pull/11._
> Part.getDuration takes autoNext.overlap into account.

- src/app/rundown/components/segment/segment.component.html
- src/app/rundown/components/segment/segment.component.spec.ts
- src/app/rundown/components/segment/segment.component.ts
This PR includes the ability of clicking on the segment header and thereby setting the first part of the segment as next part. By request of @LindvedKrvang :-)
> feat: Adds ability to set first segment part as next by clicking header

- src/app/core/enums/piece-type.ts
Add new PieceTypes that have been added in https://github.com/tv2/sofie-server/pull/10
> SOF-1539 Add new PieceTypes

- DEVELOPER.md
Draft for our developer conventions in the frontend. Logging strategy applies to all of our projects, so that is also defined on [Confluence](https://tv2cms.atlassian.net/wiki/spaces/SOF/pages/4348477470/Logging+Strategy).
> doc: Added Developer convention document.

- angular.json
- src/app/core/services/http-basic-rundown.service.ts
- src/app/core/services/http-rundown.service.ts
- src/environments/environment-interface.ts
- src/environments/environment.dev.ts
- src/environments/environment.ts
Development points to `http://localhost:3005/api` while production points to the website origin suffixed with `/api`.
> API base url configuration is based on execution environment

- src/app/app.component.ts
- src/app/shared/services/connection-error.service.ts
Reinstated event connection status as snackbar.
> chore: Reinstated event connection status as snackbar.

- src/app/rundown/components/editorial-line/editorial-line.component.ts
- src/app/rundown/components/follow-playhead-timeline/follow-playhead-timeline.component.html
- src/app/rundown/components/scrollable-timeline/scrollable-timeline.component.html
- src/app/rundown/components/scrollable-timeline/scrollable-timeline.component.ts
Added `EditorialLineComponent`  to `FollowPlayheadTimelineComponent` and `ScrollableTimelineComponent`.
> Show editorial line in rundown view

- src/app/keyboard/components/virtual-keyboard/virtual-keyboard.component.html
- src/app/keyboard/components/virtual-keyboard/virtual-keyboard.component.scss
- src/app/keyboard/components/virtual-keyboard/virtual-keyboard.component.spec.ts
- src/app/keyboard/components/virtual-keyboard/virtual-keyboard.component.ts
- src/app/keyboard/keyboard.module.ts
- src/app/producer-shelf/components/producer-shelf/producer-shelf.component.html
- src/app/producer-shelf/components/producer-shelf/producer-shelf.component.scss
- src/app/producer-shelf/components/producer-shelf/producer-shelf.component.spec.ts
- src/app/producer-shelf/components/producer-shelf/producer-shelf.component.ts
- src/app/producer-shelf/producer-shelf.module.ts
- src/app/rundown-view/components/follow-playhead-timeline/follow-playhead-timeline.component.ts
- src/app/rundown-view/components/offsetable-piece/offsetable-piece.component.scss
- src/app/rundown-view/components/rundown-header-panel/rundown-header-panel.component.scss
- src/app/rundown-view/components/rundown-view/rundown-view.component.html
- src/app/rundown-view/components/rundown-view/rundown-view.component.scss
- src/app/rundown-view/components/scrollable-timeline/scrollable-timeline.component.ts
- src/app/rundown-view/components/segment/segment.component.scss
- src/app/rundown-view/components/timeline-playhead/timeline-playhead.component.scss
- src/app/rundown-view/services/tv2-action-group.service.ts
- src/app/shared/components/draggable-shelf/draggable-shelf.component.scss
- src/app/shared/components/header/header.component.scss
- src/app/shared/components/tv2-action-card/tv2-action-card.component.html
- src/app/shared/components/tv2-action-card/tv2-action-card.component.scss
- src/app/shared/components/tv2-action-card/tv2-action-card.component.spec.ts
- src/app/shared/components/tv2-action-card/tv2-action-card.component.ts
- src/app/shared/components/tv2-action-panel/tv2-action-panel.component.html
- src/app/shared/components/tv2-action-panel/tv2-action-panel.component.scss
- src/app/shared/components/tv2-action-panel/tv2-action-panel.component.spec.ts
- src/app/shared/components/tv2-action-panel/tv2-action-panel.component.ts
- src/app/shared/shared.module.ts
- TV2 action panel component and TV2 action card component added.
- Camera and video clip actions have specialized rendering.
- Text color in the Rundown view is based on the css variable `--text-color` and is dimmed a bit.
- TV2 action panels can be configured to either wrap the actions to fill up vertical space or use horizontal scrolling to keep a strict layout.
- Showing key bindings are moved to the new component `VirtualKeyboardComponent` in preparation for SOF-1633.
> Sof 1632: Added TV2 action panels

- src/app/keyboard/abstractions/key-alias-service.ts
- src/app/keyboard/keyboard.module.ts
- src/app/keyboard/services/tv2-key-alias.service.spec.ts
- src/app/keyboard/services/tv2-key-alias.service.ts
- src/app/keyboard/services/tv2-key-binding-event.service.ts
- src/app/keyboard/services/tv2-key-binding-matcher.service.spec.ts
- src/app/keyboard/services/tv2-key-binding-matcher.service.ts
- src/app/producer-shelf/components/producer-shelf/producer-shelf.component.ts
- src/app/rundown-view/components/rundown-header-panel/rundown-header-panel.component.scss
- src/app/rundown-view/factories/key-binding.factory.ts
Introduces key aliasing, such that `Shift` is triggered by `ShiftLeft` and `ShiftRight`, `AnyEnter` is triggered by `Enter` and `NumpadEnter`, and so forth.
> SOF-1631: Key aliasing

- src/app/rundown-view/components/rundown-header-context-menu/rundown-header-context-menu.component.ts
- src/app/rundown-view/factories/key-binding.factory.ts
- src/app/shared/components/confirmation-dialog/confirmation-dialog.component.html
- src/app/shared/components/confirmation-dialog/confirmation-dialog.component.scss
- src/app/shared/components/confirmation-dialog/confirmation-dialog.component.ts
- src/app/shared/services/dialog.service.ts
- src/palettes.scss
Deactivate dialog has danger color (red).
> Deactivate dialog has danger color (red).

- src/app/core/enums/piece-type.ts
- src/app/rundown-view/factories/key-binding.factory.ts
- src/app/rundown-view/services/hardcoded-producer-key-binding.service.ts
- src/app/rundown-view/services/tv2-action-group.service.ts
- src/app/shared/components/tv2-action-card/tv2-action-card.component.scss
- src/app/shared/models/tv2-action.ts
- Remote actions are displayed in the ALL ACTIONS container.
- Camera key bindings are moved from digit keys to function keys.
- Remote actions are bound to digit keys.
> Sof 1628/remote actions

- src/app/core/enums/piece-type.ts
> SOF-1548 Add DVE PieceType

- src/app/shared/components/tv2-action-card/tv2-action-card.component.scss
- src/app/shared/models/tv2-action.ts
Renamed Tv2ActionContentType.DVE to .SPLIT_SCREEN and added simple action styling for split screens.
> Renamed Tv2ActionContentType.DVE to .SPLIT_SCREEN and added simple action styling for split screens.

- src/app/rundown-view/factories/key-binding.factory.ts
Remote actions only creates key bindings if remote number metadata is set.
> Remote actions only creates key bindings if remote number metadata is set

- src/app/settings/action-triggers/components/action-triggers-list/action-triggers-list.component.ts
- src/app/settings/action-triggers/components/action-triggers/action-triggers.component.html
- src/locale/messages.da.xlf
- src/locale/messages.en-US.xlf
- src/locale/messages.xlf
We fix the title for Action Trigger setting page and sort Action trigger list onChangeEvent
> SOF-1699 - fix action trigger page title and sort list component logic

- src/app/rundown-view/components/timeline-markers/timeline-markers.component.ts
- src/scss/_sofie-color-vars.scss
Bug fixtimeline Marker Fill Color to come from ts file
> SOF-1786 - fix timeline Marker Fill Color to come from ts file

- src/app/rundown-view/components/rundown/rundown.component.html
- src/app/rundown-view/components/rundown/rundown.component.ts
This PR makes the rundown view scroll to either the on air or next segment (if they are outside the viewport) depending on the corresponding events.
> SOF-1800 - Rundown View Follows Cursors

- src/app/shared/components/tv2-action-panel/tv2-action-panel.component.scss
Fixed typos in css variable names for action panel scroll gradient.
> Fix/action panel gradient missing.

- src/app/rundown-overview/components/rundown-overview/rundown-overview.component.scss
Fix bug in Rundown overview does not scroll
> SOF-1736 - add scroll to rundown overview

- src/app/core/enums/rundown-mode.ts
- src/app/core/models/basic-rundown.ts
- src/app/core/models/rundown.ts
- src/app/core/parsers/zod-entity-parser.service.ts
- src/app/core/parsers/zod-rundown-event-parser.service.spec.ts
- src/app/core/services/models/basic-rundown-entity.service.ts
- src/app/core/services/models/rundown-entity.service.spec.ts
- src/app/core/services/models/rundown-entity.service.ts
- src/app/core/services/rundown-timing-context-state.service.ts
- src/app/core/services/rundown-timing.service.spec.ts
- src/app/rundown-overview/components/rundown-overview/rundown-overview.component.html
- src/app/rundown-overview/components/rundown-overview/rundown-overview.component.ts
- src/app/rundown-view/components/rundown-header-context-menu/rundown-header-context-menu.component.ts
- src/app/rundown-view/components/rundown-header/rundown-header.component.html
- src/app/rundown-view/components/rundown-header/rundown-header.component.ts
- src/app/rundown-view/components/rundown/rundown.component.html
- src/app/rundown-view/components/rundown/rundown.component.ts
- src/app/rundown-view/factories/key-binding.factory.ts
- src/app/rundown-view/services/action-trigger-producer-key-binding.service.ts
- src/app/rundown-view/services/mini-shelf-cycle.service.spec.ts
- src/app/rundown-view/services/mini-shelf-navigation.service.spec.ts
- src/app/test/factories/test-entity.factory.ts
Breaking change: This changes `Rundown.isActive` to use the newly introduce `RundownMode`.
This PR must be merged at the same time as https://github.com/tv2/sofie-server/pull/105.
This PR does _not_ implement anything with the new REHEARSAL mode. It just make the frontend compatible with it.
> SOF-1566 Introduce RundownMode on Rundown

- .github/workflows/create-merge-pull-requests.yml
- .gitignore
Cherry pick the automerge yaml file to master.
Update the gitignore to match the one on develop.
> Sof 1840/cherrypick automerge file
